### ISSUE TITLE
memimage64: Writing page failed

### ISSUE THREAD

**Issue by MexHigh** [baselsayeh/coldboot-tools#1]
I'm having issues with the dumping. The dumping process stays at 00% for some minutes and then prints
```
Write error at block XXX
Writing page 0 failed
```
for every memory segment. I've followed the instructions in the `howto.txt` in the latest release zip archive of memimage64.

Any known issues why this is not working?

**Comment by baselsayeh** [comment]
What's your bios info? Laptop/MB model? Supports EFI?

It may be the bios does not support writing directly to disk via bios interrupts (I have seen this with newer EFI comparable BIOSes)

**Comment by MexHigh** [comment]
UEFI Bios Version: N1QET51W (1.26), so yes EFI support, falling back at legacy boot when UEFI is not available.
Machine Type Model: 20HES01R02.
It's a Lenovo ThinkPad T470, i5-7300U.

**Comment by baselsayeh** [comment]
Can you try this USB image and take a screenshot/picture of the screen? (Email it to me if you don't want to send it here)

https://1drv.ms/u/s!AsqipXndfFycmTiJBbBs5VvQiK-y?e=hg2yuE

This is a 8GB USB image, write it using dd, or win32 disk imager

**Comment by MexHigh** [comment]
![IMG_20210115_111029](https://user-images.githubusercontent.com/50419884/104713704-84992400-5724-11eb-9001-71880e250ef0.jpg)

![IMG_20210115_111929](https://user-images.githubusercontent.com/50419884/104713751-95e23080-5724-11eb-9dff-64402158ae0c.jpg)

**Comment by baselsayeh** [comment]
@MexHigh 
I think i know the problem
I think your BIOS does not support writing 32K at one time, or something is causing the disk driver in the BIOS not to respond after the first write

To verify:
Try opening the file 'ram.img' into a hex editor, and replace these areas with zeros: From 0xFC00 to 0x10000. Save the file and try to dump the ram again.

After dumping (it will fail), re-open 'ram.img', go to  0xFC00. Is the whole area filled with zeros?

**Comment by baselsayeh** [comment]
in addition, can you try the provided binaries, capturing the screen? (copy them into the first partition and accept the over-write)

[scraper64_test.zip](https://github.com/baselsayeh/coldboot-tools/files/5822662/scraper64_test.zip)

**Comment by MexHigh** [comment]
Thanks for your help. I'm going to look into it tomorrow.

**Comment by MexHigh** [comment]
> @MexHigh
> I think i know the problem
> I think your BIOS does not support writing 32K at one time, or something is causing the disk driver in the BIOS not to respond after the first write
> 
> To verify:
> Try opening the file 'ram.img' into a hex editor, and replace these areas with zeros: From 0xFC00 to 0x10000. Save the file and try to dump the ram again.
> 
> After dumping (it will fail), re-open 'ram.img', go to 0xFC00. Is the whole area filled with zeros?

Yes, the area is filled with zeros. But the image was full of zeros in the first place, too.


> in addition, can you try the provided binaries, capturing the screen? (copy them into the first partition and accept the over-write)
> 
> [scraper64_test.zip](https://github.com/baselsayeh/coldboot-tools/files/5822662/scraper64_test.zip)

![IMG_20210119_105814](https://user-images.githubusercontent.com/50419884/105019964-ff28b300-5a46-11eb-9aaa-4f71085a4e19.jpg)

Then it starts over with the next bytes. Same error: `Giving up, cannot dump 1`

**Comment by baselsayeh** [comment]
> > @MexHigh
> > I think i know the problem
> > I think your BIOS does not support writing 32K at one time, or something is causing the disk driver in the BIOS not to respond after the first write
> > To verify:
> > Try opening the file 'ram.img' into a hex editor, and replace these areas with zeros: From 0xFC00 to 0x10000. Save the file and try to dump the ram again.
> > After dumping (it will fail), re-open 'ram.img', go to 0xFC00. Is the whole area filled with zeros?
> 
> Yes, the area is filled with zeros. But the image was full of zeros in the first place, too.
> 
> > in addition, can you try the provided binaries, capturing the screen? (copy them into the first partition and accept the over-write)
> > [scraper64_test.zip](https://github.com/baselsayeh/coldboot-tools/files/5822662/scraper64_test.zip)
> 
> ![IMG_20210119_105814](https://user-images.githubusercontent.com/50419884/105019964-ff28b300-5a46-11eb-9aaa-4f71085a4e19.jpg)
> 
> Then it starts over with the next bytes. Same error: `Giving up, cannot dump 1`

Then i think your BIOS is incompatible, or for some reason, the BIOS cannot write to that flash drive.
You can try dumping it over PXE, or use MartijnB's memcompress, which compresses the ram and uses linux to dump the compressed segments.

Simple instructions to use memcompress:
- Download and extract the provided image
- Write the image using win32diskimager or using dd
- Create a (NTFS, FAT or EXT) partition
- Reboot to the USB drive
- Press enter on "Compress and boot linux"
- Wait for linux to boot, and type "root" as the username
- mount the fs (`mount /dev/(sda2,sdb2, sdc2, ...) /dumps`) or to mount ntfs, use `ntfs-3g /dev/(sda2, b2 or c2) /dumps`
- Be careful, use the right HDD/SSD/USB (you can use `fdisk -l`)
- after that, type `/acquisition/extract.py`
- Wait for it to complete, and reboot to your OS, and use [Those scripts](https://github.com/MartijnB/memcompress/tree/master/scripts/acquisition) to decompress the memory image

[dumper.img.zip](https://github.com/baselsayeh/coldboot-tools/files/5842921/dumper.img.zip)

**Comment by MexHigh** [comment]
Ok, thank you very much for your assistance.
