### ISSUE TITLE
Secure boot

### ISSUE THREAD

**Issue by s0i37** [baselsayeh/coldboot-tools#2]
Hello.
Thanks for your awesome tool!
That do you thing, is it possible to use `memory_scrapper` in EFI PC with secure boot?

**Comment by baselsayeh** [comment]
> Hello. Thanks for your awesome tool! That do you thing, is it possible to use `memory_scrapper` in EFI PC with secure boot?

Hi
No, this is not capable of booting in EFI systems at all, regardless of whether with or without secure boot (Unless legacy boot is available)

For efi, you can use MartijnB's memcompress. It depends on syslinux, and syslinux can boot in EFI systems (don't think that it can boot in Secure boot systems)
