### ISSUE TITLE
Recording to a USB flash drive

### ISSUE THREAD

**Issue by Srg-Blmv** [baselsayeh/coldboot-tools#3]
Hello.
Help me please.
I can't create a flash drive, I do the following steps
1) dd if=grldr.mbr of=/dev/sdc conv=notrunc
2) sudo fdisk /dev/sdc
2.1) key n -> default -> +size 100M
2.2) key a -> 1
2.3) n key -> default -> default
2.4) w key

3) sudo mkfs.fat /dev/sdc1
4) sudo mkfs.ntfs /dev/sdc2

5) sudo mount /dev/sdc1 /media
5.1) cd Cold_boot_attack/bios_memimage && sudo cp */media
5.2) sudo umount /media

6) sudo mount /dev/sdc2 /media
6.1) tranсute --size 6000M /media/ram.img
6.2) sudo umount /media

I have tried many options and always get errors like: Error 61: Too many fragments.

Empirically, I found out that the error appears at step: map (hd0,1)/ram.img (hd0)

**Comment by baselsayeh** [comment]
Hello

Grub4Dos expects the ram image (ram.img) to be contiguous inside the second partition.

Would I suggest is to either

  *   make the ram.img in another location (hdd, ram, ...) and then re-format the second partition and copy the ram.img file to the second partition

  *   Or run a disk defragmentation tool, it should make the ram image file contiguous





________________________________
From: SeregaEngineer ***@***.***>
Sent: Saturday, December 30, 2023 11:34 AM
To: baselsayeh/coldboot-tools ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [baselsayeh/coldboot-tools] Recording to a USB flash drive (Issue #3)


Hello.
Help me please.
I can't create a flash drive, I do the following steps

  1.  dd if=grldr.mbr of=/dev/sdc conv=notrunc

  2.  sudo fdisk /dev/sdc
2.1) key n -> default -> +size 100M
2.2) key a -> 1
2.3) n key -> default -> default
2.4) w key

  3.  sudo mkfs.fat /dev/sdc1

  4.  sudo mkfs.ntfs /dev/sdc2

  5.  sudo mount /dev/sdc1 /media
5.1) cd Cold_boot_attack/bios_memimage && sudo cp */media
5.2) sudo umount /media

  6.  sudo mount /dev/sdc2 /media
6.1) tranсute --size 6000M /media/ram.img
6.2) sudo umount /media

I have tried many options and always get errors like: Error 61: Too many fragments.

**Comment by Srg-Blmv** [comment]
Thank you very much.
After the dump was copied, the entire file system was broken. But I'll try to figure that out

**Comment by TekotovaVA** [comment]
I perform all the same actions as SeregaEngineer, but bois does not see usb when booting
